services:
  postgres:
    image: postgres:17-alpine
    container_name: lab5_postgres
    environment:
      POSTGRES_DB: lab5
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: lab5_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
