spring:
  application:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
  profiles:
    active: "@spring.profiles.active@"
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

instance:
  name: ${INSTANCE_NAME}

server:
  port: ${SERVER_PORT}

queue:
  processed:
    history-limit: ${QUEUE_PROCESSED_HISTORY_LIMIT}
  consumer:
    poll-delay-ms: ${QUEUE_CONSUMER_POLL_DELAY_MS}
    processing-delay-ms: ${QUEUE_CONSUMER_PROCESSING_DELAY_MS}
