spring:
  application:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
  data:
    redis:
      host: localhost
      port: 6379

instance:
  name: "default-instance-name"

server:
  port: 8067
